#ifndef REDUNDANCY_H
#define REDUNDANCY_H

enum REDUNDANCY
{
  REDUNDANCY_NO,
  REDUNDANCY_CHANGE,
  REDUNDANCY_BS,
  //REDUNDANCY_FREE,
  REDUNDANCY_ATHR,
  REDUNDANCY_ATMR,
  REDUNDANCY_AERT,
  REDUNDANCY_ATTS,
  REDUNDANCY_FREE,
  REDUNDANCY_SLAVE,
  REDUNDANCY_MASTER,
  REDUNDANCY_FAILSAFE,
  REDUNDANCY_LAST
};

enum REDUNDANCY_MOTOR
{
  REDUNDANCY_MOTOR_HOST_ONE,
  REDUNDANCY_MOTOR_HOST_TWO,
  REDUNDANCY_MOTOR_ONE,
  REDUNDANCY_MOTOR_TWO,
  REDUNDANCY_MOTOR_FREE,
  REDUNDANCY_MOTOR_MASTER,
  REDUNDANCY_MOTOR_LAST
};

uint8_t REDUNDANCY_Process(void);
uint8_t REDUNDANCY_MotorModeGrowings(void);

#endif
